### PR TITLE
Update strlib.inc

### PR DESCRIPTION
**Pull request by juanpenia**
little modification so translate.inc (https://github.com/oscar-broman/samp-translate) can recognize it.

### CODE REVIEW

**Comment by spacemud** [comment]
This PR breaks scripts compiled with the default SA-MP compiler, or those using the modified one in compatibility mode. You should use the manual style include guards instead to avoid this:

```pawn
#if defined _strlib_included
	#endinput
#endif
#define _strlib_included
```

It's documented [here](https://github.com/pawn-lang/compiler/wiki/Include-Guards).

**Comment by juanpenia** [comment]
`#if defined STRLIB_INC
	#endinput
#endif
#define STRLIB_INC`

this instead of what I suggested before works both with the default compiler and the modified one.

**Comment by Y-Less** [comment]
I'd suggest `_INC_strlib`, it's a fairly common pattern for this, since it mirrors the compiler default method.

**Comment by juanpenia** [comment]
Changing the inc to INC just did the job and did not break the default samp compiler, lmao.

As you may have noticed, I'm not the greatest of the programmers.. Just ditch my others pull requests, lol.

**Pull request merged**
